### ISSUE TITLE
[Enhancement] Blacklist

### ISSUE THREAD

**Issue by ANormalRaft** [iMoonDay/Soulbound#3]
It would be nice for a blacklist to be added if we'd want a few items to not be able to be enchanted with SoulBound (whether through the anvil or the enchantment table)

(I am playing on the 1.19.2 version on Forge)

**Comment by iMoonDay** [comment]
OK, I will add black/white list function for all versions next version.

**Comment by iMoonDay** [comment]
All versions have been updated, hope you like this blacklist
