### ISSUE TITLE
Soulbound on Books not Working.

### ISSUE THREAD

**Issue by NachoWarlock** [iMoonDay/Soulbound#5]
No matter what I do I can't get soulbound to appear while enchanting a book. Is this a problem with enchanting power making it more rare? the config is standard besides a netherite longsword in the black list and the compatibility in the blacklist and default and the enchantment is not set to treasure.
Also, just a thought, could there be an option to make this a villager trade?

**Comment by iMoonDay** [comment]
I just realized that it was a mistake on my part that caused the book's enchantment feature to not work for soulbound, I'll fix it in the next version!

**Comment by iMoonDay** [comment]
New version has been fixed and option has been added.
