### ISSUE TITLE
Config option to disable obtaining in survival

### ISSUE THREAD

**Issue by den-commits** [iMoonDay/Soulbound#6]
Hello,

I am using Fabric 1.20.1 and would like to assign this enchantment via /give commands (NBT tag) only.
Would it be possible to add a config option to outright remove all survival methods of obtaining the enchant? I.e. Librarian trade, Wandering Trader trade, fishing, and any other way it may be implemented.

Thank you!

**Comment by iMoonDay** [comment]
Try the new version to see if the features are what you want

**Comment by den-commits** [comment]
Looks good! Thanks for the quick update!
