### ISSUE TITLE
Update to 1.21

### ISSUE THREAD

**Issue by Bruhnanza** [iMoonDay/Soulbound#7]
Are there any plans to update the mod to support Minecraft 1.21? I understand if it is not something immediate, but with the new datapack features for enchantments it may be beneficial once utilized.

**Comment by iMoonDay** [comment]
Mojang changed the code about enchantments, I need some time to rewrite it :(

**Comment by Bruhnanza** [comment]
That makes sense, I figured I would create the issue for continuity sake. Thank you for the response and good luck with the rewrite when the time comes.

**Comment by iMoonDay** [comment]
I updated fabric to 1.21. if you need the forge version, wait a little longer, I don't have much free time these days.

**Comment by Bruhnanza** [comment]
No worries, Fabric is the superior mod loader anyhow. Thank you!
