### ISSUE TITLE
foger1.20.1 0.8版本与旅行背包在一起使用时会崩溃

### ISSUE THREAD

**Issue by EtherealAirRhyme** [iMoonDay/Soulbound#8]
这是崩溃报告:https://ww0.lanzouv.com/izocJ256fedg；
尝试了Modrinth里的0.9版本，但似乎不会生效XP

**Comment by iMoonDay** [comment]
灵魂绑定的forge版本太旧了，没有兼容当前最新版本的旅行背包，下次更新会修复，大概在一周内更新

**Comment by iMoonDay** [comment]
如果急用，可以尝试将旅行背包降级到1.20.1-9.1.7版本，但是不确定这个旧版本会不会与其他模组不兼容

**Comment by EtherealAirRhyme** [comment]
> 灵魂绑定的forge版本太旧了，没有兼容当前最新版本的旅行背包，下次更新会修复，大概在一周内更新

非常感谢，灵魂绑定功能实在是太稀少了😭

**Comment by iMoonDay** [comment]
是的，很多大型模组都自带这个附魔，所以几乎没人单独提取出来做成一个小模组

**Comment by EtherealAirRhyme** [comment]
> 如果急用，可以尝试将旅行背包降级到1.20.1-9.1.7版本，但是不确定这个旧版本会不会与其他模组不兼容

悲，很遗憾，去看了一遍旅行背包的更新日志，的确会产生一些比较严重的兼容问题XP

**Comment by EtherealAirRhyme** [comment]
> 是的，很多大型模组都自带这个附魔，所以几乎没人单独提取出来做成一个小模组

他们很难寻找，如果需要意味着不得不加入很多附加内容，这个模组简直是救星
和朋友们组计划组了个用末日路途当基底的服务器，打算长期游玩，如果开启死亡不掉落的话，有很没有内味，关闭的话，代价又有点太大了

**Comment by iMoonDay** [comment]
更新了，试一下应该修复了

**Comment by EtherealAirRhyme** [comment]
> 更新了，试一下应该修复了

感谢！这个模组如期生效了
