### ISSUE TITLE
Not compatible with Universal Graves mod.

### ISSUE THREAD

**Issue by pil0lo** [iMoonDay/Soulbound#9]
https://www.curseforge.com/minecraft/mc-mods/universal-graves

The Universal Graves mode is a mode that creates a gravestone when you die.
Soulbound enchanted items are also included when a tombstone is created in Universal Graves mode...
Can't it stay in inventory?

**Comment by iMoonDay** [comment]
Open the Universal Graves mod's config file, find the _**blocked_enchantments**_ in there, and add **_soulbound:soulbound_** to it.

**Comment by pil0lo** [comment]
The blocks_enchantments file is not visible.
Which file exactly do I need to find?


![1](https://github.com/user-attachments/assets/b1ba25d7-eaa1-4f8a-a026-6a850054a806)

{
  "type": "minecraft:block",
  "pools": [
    {
      "bonus_rolls": 0.0,
      "conditions": [
        {
          "condition": "minecraft:survives_explosion"
        }
      ],
      "entries": [
        {
          "type": "minecraft:item",
          "name": "universal_graves:visual_grave"
        }
      ],
      "rolls": 1.0
    }
  ]
}

**Comment by iMoonDay** [comment]
./config/universal-graves/config.json

**Comment by pil0lo** [comment]
C:\Users\user\AppData\Roaming\.minecraft\config\universal-graves

Can't find it in the list.....
[blocks_enchantments]
![1](https://github.com/user-attachments/assets/9c779fe7-242b-4132-a3eb-fd25393595d7)


{
  "_comment": "Before changing anything, see https://github.com/Patbox/UniversalGraves#configuration",
  "config_version": 4,
  "protection": {
    "non_owner_protection_time": 900,
    "self_destruction_time": 1800,
    "drop_items_on_expiration": true,
    "attackers_bypass_protection": false,
    "use_real_time": false
  },
  "interactions": {
    "unlocking_cost": {
      "type": "free",
      "count": 0
    },
    "give_death_compass": true,
    "enable_use_death_compass_to_open_gui": true,
    "enable_click_to_open_gui": true,
    "shift_and_use_quick_pickup": true,
    "allow_remote_protection_removal": true,
    "allow_remote_breaking": true,
    "allow_remote_unlocking": false
  },
  "storage": {
    "experience_type": "percent_points",
    "experience_percent:setting_value": 100.0,
    "can_store_only_xp": false,
    "alternative_experience_entity": false,
    "blocked_enchantments": []
  },
  "placement": {
    "player_grave_limit": -1,
    "replace_any_block": false,
    "max_distance_from_source_location": 8,
    "shift_location_on_failure": true,
    "max_shift_tries": 5,
    "max_shift_distance": 40,
    "generate_on_top_of_fluids": false,
    "generate_on_ground": false,
    "create_gravestone_after_emptying": false,
    "restore_replaced_block_after_player_breaking": true,
    "cancel_creation_for_damage_types": {},
    "cancel_creation_for_ignored_attacker_types": {},
    "blocking_predicates": [],
    "block_in_protected_area": {},
    "blacklisted_worlds": [],
    "blacklisted_areas": {},
    "creation_default_failure_text": "<red><lang:'text.graves.creation_failed':'<gold>${position}':'<yellow>${world}'>",
    "creation_claim_failure_text": "<red><lang:'text.graves.creation_failed_claim':'<gold>${position}':'<yellow>${world}'>"
  },
  "teleportation": {
    "cost": {
      "type": "creative",
      "count": 1
    },
    "required_time": 5,
    "y_offset": 1.0,
    "invincibility_time": 2,
    "allow_movement_while_waiting": false,
    "text": {
      "timer": "<lang:'text.graves.teleport.teleport_timer':'${time}'>",
      "timer_allow_moving": "<lang:'text.graves.teleport.teleport_timer_moving':'${time}'>",
      "location": "<lang:'text.graves.teleport.teleport_location':'${position}'>",
      "canceled": "<red><lang:'text.graves.teleport.teleport_cancelled'>"
    }
  },
  "model": {
    "default": "default",
    "alternative": [],
    "hide_f3_debug_lines": true,
    "gravestone_item_base": "minecraft:skeleton_skull"
  },
  "ui": {
    "title": "<lang:'text.graves.players_grave':'${player}'>",
    "admin_title": "<lang:'text.graves.admin_graves'>",
    "list_grave_icon": {
      "base": {
        "icon": "minecraft:chest",
        "text": [
          "${position} <gray>(${world})",
          "<yellow>${death_cause}",
          "<gray><lang:'text.graves.items_xp':'<white>${item_count}':'<white>${xp}'>",
          "<blue><lang:'text.graves.protected_time':'<white>${protection_time}'>",
          "<red><lang:'text.graves.break_time':'<white>${break_time}'>"
        ]
      },
      "alt": {
        "icon": "minecraft:trapped_chest",
        "text": [
          "${position} <gray>(${world})",
          "<yellow>${death_cause}",
          "<gray><lang:'text.graves.items_xp':'<white>${item_count}':'<white>${xp}'>",
          "<blue><lang:'text.graves.not_protected'>",
          "<red><lang:'text.graves.break_time':'<white>${break_time}'>"
        ]
      }
    },
    "admin_list_grave_icon": {
      "base": {
        "icon": "minecraft:chest",
        "text": [
          "<dark_gray>[<white>${player}</>]</> ${position} <gray>(${world})",
          "<yellow>${death_cause}",
          "<gray><lang:'text.graves.items_xp':'<white>${item_count}':'<white>${xp}'>",
          "<blue><lang:'text.graves.protected_time':'<white>${protection_time}'>",
          "<red><lang:'text.graves.break_time':'<white>${break_time}'>"
        ]
      },
      "alt": {
        "icon": "minecraft:trapped_chest",
        "text": [
          "<dark_gray>[<white>${player}</>]</> ${position} <gray>(${world})",
          "<yellow>${death_cause}",
          "<gray><lang:'text.graves.items_xp':'<white>${item_count}':'<white>${xp}'>",
          "<blue><lang:'text.graves.not_protected'>",
          "<red><lang:'text.graves.break_time':'<white>${break_time}'>"
        ]
      }
    },
    "grave_info": {
      "base": {
        "icon": "minecraft:oak_sign",
        "text": [
          "${position} <gray>(${world})",
          "<yellow>${death_cause}",
          "<gray><lang:'text.graves.items_xp':'<white>${item_count}':'<white>${xp}'>",
          "<blue><lang:'text.graves.protected_time':'<white>${protection_time}'>",
          "<red><lang:'text.graves.break_time':'<white>${break_time}'>"
        ]
      },
      "alt": {
        "icon": "minecraft:oak_sign",
        "text": [
          "${position} <gray>(${world})",
          "<yellow>${death_cause}",
          "<gray><lang:'text.graves.items_xp':'<white>${item_count}':'<white>${xp}'>",
          "<blue><lang:'text.graves.not_protected'>",
          "<red><lang:'text.graves.break_time':'<white>${break_time}'>"
        ]
      }
    },
    "unlock_grave": {
      "base": {
        "icon": "minecraft:gold_ingot",
        "text": [
          "<#ffd257><lang:'text.graves.gui.unlock_grave'>",
          "<white><lang:'text.graves.gui.cost'> <#cfcfcf>${cost}"
        ]
      },
      "alt": {
        "icon": "minecraft:gold_ingot",
        "text": [
          "<dark_gray><lang:'text.graves.gui.unlock_grave'>",
          "<white><lang:'text.graves.gui.cost'> <#cfcfcf>${cost} <gray>(<red><lang:'text.graves.gui.cost.not_enough'></red>)"
        ]
      }
    },
    "previous_button": {
      "base": {
        "icon": {
          "id": "universal_graves:icon",
          "count": 1,
          "components": {
            "universal_graves:texture": "previous_page"
          }
        },
        "text": "<lang:'text.graves.gui.previous_page'>"
      },
      "alt": {
        "icon": {
          "id": "universal_graves:icon",
          "count": 1,
          "components": {
            "universal_graves:texture": "previous_page_blocked"
          }
        },
        "text": "<dark_gray><lang:'text.graves.gui.previous_page'>"
      }
    },
    "next_button": {
      "base": {
        "icon": {
          "id": "universal_graves:icon",
          "count": 1,
          "components": {
            "universal_graves:texture": "next_page"
          }
        },
        "text": "<lang:'text.graves.gui.next_page'>"
      },
      "alt": {
        "icon": {
          "id": "universal_graves:icon",
          "count": 1,
          "components": {
            "universal_graves:texture": "next_page_blocked"
          }
        },
        "text": "<dark_gray><lang:'text.graves.gui.next_page'>"
      }
    },
    "remove_protection_button": {
      "base": {
        "icon": {
          "id": "universal_graves:icon",
          "count": 1,
          "components": {
            "universal_graves:texture": "remove_protection"
          }
        },
        "text": "<red><lang:'text.graves.gui.remove_protection'>"
      },
      "alt": {
        "icon": {
          "id": "universal_graves:icon",
          "count": 1,
          "components": {
            "universal_graves:texture": "remove_protection"
          }
        },
        "text": [
          "<red><lang:'text.graves.gui.remove_protection'>",
          "<dark_red><bold><lang:'text.graves.gui.cant_reverse'>",
          "",
          "<white><lang:'text.graves.gui.click_to_confirm'>"
        ]
      }
    },
    "break_grave_button": {
      "base": {
        "icon": {
          "id": "universal_graves:icon",
          "count": 1,
          "components": {
            "universal_graves:texture": "break_grave"
          }
        },
        "text": "<red><lang:'text.graves.gui.break_grave'>"
      },
      "alt": {
        "icon": {
          "id": "universal_graves:icon",
          "count": 1,
          "components": {
            "universal_graves:texture": "break_grave"
          }
        },
        "text": [
          "<red><lang:'text.graves.gui.break_grave'>",
          "<dark_red><bold><lang:'text.graves.gui.cant_reverse'>",
          "",
          "<white><lang:'text.graves.gui.click_to_confirm'>"
        ]
      }
    },
    "quick_pickup_button": {
      "icon": {
        "id": "universal_graves:icon",
        "count": 1,
        "components": {
          "universal_graves:texture": "quick_pickup"
        }
      },
      "text": "<red><lang:'text.graves.gui.quick_pickup'>"
    },
    "fetch_button": {
      "base": {
        "icon": "minecraft:lead",
        "text": "<yellow><lang:'text.graves.gui.fetch'>"
      },
      "alt": {
        "icon": "minecraft:lead",
        "text": "<yellow><lang:'text.graves.gui.fetch'>"
      }
    },
    "teleport_button": {
      "base": {
        "icon": "minecraft:ender_pearl",
        "text": [
          "<#a52dfa><lang:'text.graves.gui.teleport'>",
          "<white><lang:'text.graves.gui.cost'> <#cfcfcf>${cost}"
        ]
      },
      "alt": {
        "icon": "minecraft:ender_pearl",
        "text": [
          "<dark_gray><lang:'text.graves.gui.teleport'>",
          "<white><lang:'text.graves.gui.cost'> <#cfcfcf>${cost} <gray>(<red><lang:'text.graves.gui.cost.not_enough'></red>)"
        ]
      }
    },
    "back_button": {
      "icon": "minecraft:structure_void",
      "text": "<red><lang:'text.graves.gui.quick_pickup'>"
    },
    "bar": {
      "icon": "minecraft:white_stained_glass_pane",
      "text": ""
    }
  },
  "text": {
    "grave_created": "<white><lang:'text.graves.created_at_expire':'<yellow>${position}':'<gray>${world}':'<red>${break_time}'>",
    "protection_ended": "<red><lang:'text.graves.no_longer_protected':'<gold>${position}':'<white>${world}':'<yellow>${item_count}'>",
    "grave_expired": "<red><lang:'text.graves.expired':'<gold>${position}':'<white>${world}':'<yellow>${item_count}'>",
    "grave_broken": "<gray><lang:'text.graves.somebody_broke':'<white>${position}':'<white>${world}':'<white>${item_count}'>",
    "grave_access_payment_no_access": "<red><lang:'text.graves.grave_unlock_payment.no_access'>",
    "grave_payment_accepted": "<white><lang:'text.graves.grave_unlock_payment.accepted'>",
    "grave_payment_failed": "<red><lang:'text.graves.grave_unlock_payment.failed':'<yellow>${cost}'>",
    "years_suffix": "y",
    "days_suffix": "d",
    "hours_suffix": "h",
    "minutes_suffix": "m",
    "seconds_suffix": "s",
    "infinity": "∞",
    "date_format": "dd.MM.yyyy, HH:mm",
    "world_names": {}
  }
}

**Comment by iMoonDay** [comment]
There should be some differences from version to version, I saw your screenshot, it's the **_blocked_enchantments_** located under _**storage**_

**Comment by pil0lo** [comment]
[blocked_enchants]List found. You just have to write [soulbound:soulbound] in [] in this list, right?
thank you
I'll go outside for a while and check when I get home.
thank you!!!

**Comment by iMoonDay** [comment]
Yes, but it needs to be in quotes, it should be [“soulbound:soulbound”]

**Comment by pil0lo** [comment]
The enchantments marked in squares are the same enchantments.
I wrote it down as you said, but it failed.
I wrote it in Korean and also in English.

![1](https://github.com/user-attachments/assets/d687b108-900d-4928-bfb2-af8d45e74856)
![2](https://github.com/user-attachments/assets/35d76939-ec1d-4a2f-a744-835362518497)
![3](https://github.com/user-attachments/assets/71a12de0-7743-4934-b356-783932ff8c1f)

**Comment by iMoonDay** [comment]
Are you sure this soulbound enchantment is from my mod? I remember my mod wasn't translated into Korean

**Comment by iMoonDay** [comment]
I seem to have found the problem, I misspelled the quotes before and the mod didn't recognize them correctly, change them to `["soulbound:soulbound"]`

**Comment by pil0lo** [comment]
When I added various enchantment modes, there were so many that I changed the names to Korean to categorize them.

  "storage": {
    "experience_type": "percent_points",
    "experience_percent:setting_value": 100.0,
    "can_store_only_xp": false,
    "alternative_experience_entity": false,
    "blocked_enchantments": ["soulbound:soulbound"]

If you still die, all your items will be lost.
If you can't make items disappear, I think you'll have to remove the "Universal Graves" mod.

[ko_kr.json](https://github.com/user-attachments/files/16358438/ko_kr.json)

**Comment by iMoonDay** [comment]
I'm kind of missing your point. Is it still not in effect?

**Comment by pil0lo** [comment]
When you die, all items are still lost.

**Comment by iMoonDay** [comment]
Won't it now be put into a tombstone, but dropped normally?

**Comment by pil0lo** [comment]
I uploaded it as a YouTube video.
If you look at your inventory, it disappears when you die.

https://youtu.be/pIwDOSMY6lE

**Comment by iMoonDay** [comment]
I just tested it and realized it's a bug specific to version 1.21, wait for me to fix it.

**Comment by iMoonDay** [comment]
Unfortunately, I tried to fix it, and in the end it turned out to be a problem with the Universal Graves mod, to whom I've filed an ISSUE.

**Comment by iMoonDay** [comment]
Universal Graves mod has been updated, you can try it to see if it's fixed.

**Comment by pil0lo** [comment]
It works fine.
It's solved.
Thank you.
